### PR TITLE
Support for "try" and "optional" modes

### PR DESCRIPTION
**Pull request by richardlay**
If the authorization header is missing we need to pass null as the error message, otherwise hapi will not try other strategies. It will also fail if the mode is on 'try'.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Can you add a test for this?

**Comment by richardlay** [comment]
I've added a handful of tests, and actually had to make some more code changes. Please review. I've based this change on the following snippet from Hapi's Auth tutorial page:

If mode is set to 'optional' the strategy will still be applied to all routes lacking auth config, but in this case the user does not need to be authenticated. Authentication data is optional, but must be valid if provided.

The last mode setting is 'try' which, again, applies to all routes lacking an auth config. The difference between 'try' and 'optional' is that with 'try' invalid authentication is accepted, and the user will still reach the route handler.

**Comment by richardlay** [comment]
And also from the Hapi api reference:

When the scheme authenticate() method implementation calls reply() with an error condition, the specifics of the error affect whether additional authentication strategies will be attempted if configured for the route. If the err returned by the reply() method includes a message, no additional strategies will be attempted. If the err does not include a message but does include a scheme name (e.g. Boom.unauthorized(null, 'Custom')), additional strategies will be attempted in order of preference.

**Comment by AdriVanHoudt** [comment]
Ok so there are definitely things to improve with the modules error handling. But after looking at https://github.com/hapijs/hapi-auth-basic/blob/master/lib/index.js which this module is based on and which is probably the best example of a hapi auth scheme it does not seem like we need to handle try mode. Looking at the auth handling in hapi https://github.com/hapijs/hapi/blob/master/lib/auth.js#L181 it seems it takes care of the modes.
So I would like to match the handling to that of auth-basic. Either you update the PR or I will do the changes. Thanks for pointing this out!

**Pull request closed without merging**
